<?php

declare(strict_types=1);

return [
    'dashboard' => [DashboardController::class, 'index'],
    'login' => [AuthController::class, 'showLogin'],
    'do_login' => [AuthController::class, 'login'],
    'forgot_password' => [AuthController::class, 'forgotPassword'],
    'do_forgot_password' => [AuthController::class, 'processForgotPassword'],
    'reset_password' => [AuthController::class, 'showResetForm'],
    'do_reset_password' => [AuthController::class, 'resetPassword'],
    'logout' => [AuthController::class, 'logout'],
    'portal_siswa' => [PortalSiswaController::class, 'index'],
    'portal_siswa_absensi' => [PortalSiswaController::class, 'absensi'],
    'portal_siswa_jadwal' => [PortalSiswaController::class, 'jadwal'],
    'guru' => [GuruController::class, 'index'],
    'siswa' => [SiswaController::class, 'index'],
    'import' => [ImportController::class, 'index'],
    'kelas' => [KelasController::class, 'index'],
    'jurusan' => [JurusanController::class, 'index'],
    'absensi_guru' => [AbsensiGuruController::class, 'index'],
    'absensi_siswa' => [AbsensiSiswaController::class, 'index'],
    'laporan_absensi' => [LaporanAbsensiController::class, 'index'],
    'laporan_keterlambatan' => [LaporanTambahanController::class, 'keterlambatan'],
    'laporan_kelas' => [LaporanTambahanController::class, 'kelas'],
    'jadwal' => [JadwalController::class, 'index'],
    'fingerprint_devices' => [FingerprintController::class, 'index'],
    'fingerprint_logs' => [FingerprintController::class, 'logs'],
    'whatsapp_config' => [WhatsAppController::class, 'index'],
    'whatsapp_logs' => [WhatsAppController::class, 'logs'],
    'whatsapp_templates' => [WhatsAppController::class, 'templates'],
    'automation' => [AutomationController::class, 'index'],
    'health' => [HealthController::class, 'index'],
    'automation_trigger' => [AutomationController::class, 'trigger'],
    'profile' => [ProfileController::class, 'index'],
    'profile_edit' => [ProfileController::class, 'edit'],
    'profile_update' => [ProfileController::class, 'update'],
    'activity_logs' => [ActivityLogController::class, 'index'],
    'settings' => [SettingsController::class, 'index'],
    'settings_update' => [SettingsController::class, 'update'],
    'system_stats' => [SystemStatsController::class, 'index'],
    'absensi_siswa_harian' => [AbsensiSiswaHarianController::class, 'index'],
    'pengaduan' => [PengaduanController::class, 'index'],
    'pengaduan_form' => [PublicPengaduanController::class, 'form'],
    'pengaduan_submit' => [PublicPengaduanController::class, 'submit'],
];
